version: '3.8'

services:
  database-service:
    image: postgres:latest
    container_name: db_service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=main_db
    ports:
      - "5432:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data
      - ./data_files:/data
    networks:
      - app-network

  database-admin:
    image: adminer
    container_name: adminer_interface
    ports:
      - "8080:8080"
    depends_on:
      - database-service
    networks:
      - app-network

volumes:
  data_volume:
    driver: local

networks:
  app-network:
    driver: bridge
